### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by CaterinaFabbri** [kadirnar/bytetrack-pip#4]
(venv39) ➜ pip install bytetracker==0.3.2
Collecting bytetracker==0.3.2
  Downloading bytetracker-0.3.2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torch==1.13.0
  Downloading torch-1.13.0-cp39-none-macosx_11_0_arm64.whl (55.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 MB 7.9 MB/s eta 0:00:00
Collecting scipy==1.9.3
  Downloading scipy-1.9.3-cp39-cp39-macosx_12_0_arm64.whl (28.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.6/28.6 MB 10.4 MB/s eta 0:00:00
Collecting lap==0.4.0
  Downloading lap-0.4.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy<1.26.0,>=1.18.5
  Using cached numpy-1.24.3-cp39-cp39-macosx_11_0_arm64.whl (13.9 MB)
Collecting typing-extensions
  Downloading typing_extensions-4.6.1-py3-none-any.whl (31 kB)
Building wheels for collected packages: bytetracker
  Building wheel for bytetracker (pyproject.toml) ... done
  Created wheel for bytetracker: filename=bytetracker-0.3.2-py3-none-any.whl size=11476 sha256=2c73e7475d443cbb88f2a82e1706985ed350f3fab5914c56ccef50d9cf2afc7d
  Stored in directory: /Users/user/Library/Caches/pip/wheels/18/f0/91/90b451abc89b970fb868fbb6feb49876e1ed0c842a41150d08
Successfully built bytetracker
Installing collected packages: lap, typing-extensions, numpy, torch, scipy, bytetracker
  DEPRECATION: lap is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lap ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/private/var/folders/47/ljdps0gn1qldfj69y4ql75fw0000gn/T/pip-install-khw5zzeh/lap_372b942a921c4153adbe868c7f83c466/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/47/ljdps0gn1qldfj69y4ql75fw0000gn/T/pip-install-khw5zzeh/lap_372b942a921c4153adbe868c7f83c466/setup.py", line 236, in <module>
          setup_package()
        File "/private/var/folders/47/ljdps0gn1qldfj69y4ql75fw0000gn/T/pip-install-khw5zzeh/lap_372b942a921c4153adbe868c7f83c466/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by kadirnar** [comment]
```
pip install numpy
```

**Comment by swdee** [comment]
I received the same error and fixed it with.

```
pip install numpy==1.25.2
```

Then run install again.
```
pip install bytetracker
```

**Comment by JJjulle** [comment]
still the same issues.

**Comment by YannLepoittevin** [comment]
It works out of the box if you clone the repository and install the local package. I wasn't able to make a `pip install` work either.
